#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# cygwin requires special treatment...

if  uname | grep -iq CYGWIN
then
    JARFILE=`cygpath -w "$DIR/spekl-package-manager-0.1.0-SNAPSHOT-standalone.jar"`
    ENV_FLAGS="-Dshellenv=CYGWIN"
else
    JARFILE="$DIR/spekl-package-manager-0.1.0-SNAPSHOT-standalone.jar"
    ENV_FLAGS="-Dshellenv=other"
fi

PATH="$DIR/tools/Git/bin/":$PATH


"$DIR/java/bin/java" $ENV_FLAGS -jar "$JARFILE" $@
 
